version: '3.0'

services:
  pg:
    container_name: postgres_pokemon_api
    image: postgres
    environment:
      POSTGRES_PASSWORD: secure
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokemon_api
    volumes:
      - ./PokemonApi/:/app
    ports:
      - "3000:3000"
    depends_on:
      - pg
    environment:
      PG_PASSWORD: secure 
      PG_USER: postgres
      PG_HOST: postgres_pokemon_api
