openapi: 3.0.1
info:
  version: v1
  title: Pokemon API
paths:
  "/api/v1/pokemons":
    get:
      summary: Retrieves all pokemons
      tags:
        - Pokemons
      parameters:
        - in: query
          name: available
          schema:
            type: string
            format: boolean
            example: true
          description: filter by availability
      responses:
        '200':
          description: All pokemons
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/arrayOfPokemons"
  "/api/v1/pokemons/{id}":
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: Pokemon ID
    get:
      summary: Retrieves a pokemon
      tags:
        - Pokemons
      responses:
        '200':
          description: Pokemon found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/pokemon"
  "/api/v1/combats":
    get:
      summary: Retrieves all combats
      tags:
        - Combats
      responses:
        '200':
          description: Combats found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/arrayOfCombats"
    post:
      summary: Simulates a fight between two pokemons
      description: Fill in two pokemons IDs and a fight will be simulated
      tags:
        - Combats
      requestBody:
        description: Fill in two pokemons IDs and a fight will be simulated. The attacker attacks first with one of his moves. The fight is over when one's got HP under zero. The winner earns the experience of its opponent. When a pokemon has HP < 0, he turns unavailable and can't fight anymore.
        content:
          application/json:
            schema:
              type: object
              properties:
                attacker_id:
                  type: integer
                opponent_id:
                  type: integer
      responses:
        '201':
          description: Simulation created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/combat"

servers:
  - url: http://{defaultHost}:3000
    variables:
      defaultHost:
        default: localhost

components:
  schemas:
    arrayOfPokemons:
      type: array
      items:
        $ref: '#/components/schemas/pokemon'
    pokemon:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          example: 'Bulbasaur'
        p_type:
          type: string
          example: 'Grass'
        hp:
          type: integer
          example: '100'
        moves:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              damage:
                type: integer
        available:
          type: boolean
    combat:
      type: object
      properties:
        id:
          type: integer
        winner_id:
          type: integer
        xp_gain:
          type: integer
        attacker_id:
          type: integer
        attacker_name:
          type: string
        opponent_id:
          type: integer
        opponent_name:
          type: string
        actions:
          $ref: "#/components/schemas/arrayOfActions"
    action:
      type: object
      properties:
        id:
          type: integer
        pokemon_name:
          type: string
        move_name:
          type: string
        move_damage:
          type: integer

    arrayOfCombats:
      type: array
      items:
        $ref: '#/components/schemas/combat'
    arrayOfActions:
      type: array
      items:
        $ref: '#/components/schemas/action'
